import Foundation

public struct CodexShellIntegration {
    public let supportDirectory: URL
    public let homeDirectory: URL
    private let fileManager: FileManager

    private let beginMarker = "# >>> Codex Model Switcher shell hook >>>"
    private let endMarker = "# <<< Codex Model Switcher shell hook <<<"

    public init(
        supportDirectory: URL = CodexModelSwitcherAppPaths.supportDirectory,
        homeDirectory: URL = FileManager.default.homeDirectoryForCurrentUser,
        fileManager: FileManager = .default
    ) {
        self.supportDirectory = supportDirectory
        self.homeDirectory = homeDirectory
        self.fileManager = fileManager
    }

    public var activeProfileEnv: URL {
        supportDirectory.appendingPathComponent("active-profile.env")
    }

    public var shellHook: URL {
        supportDirectory.appendingPathComponent("codex-shell-hook.sh")
    }

    public func writeActiveProfile(_ profile: CodexProfile) throws {
        try fileManager.createDirectory(at: supportDirectory, withIntermediateDirectories: true)
        try activeProfileEnvContent(for: profile)
            .write(to: activeProfileEnv, atomically: true, encoding: .utf8)
    }

    @discardableResult
    public func installShellHook() throws -> [URL] {
        try fileManager.createDirectory(at: supportDirectory, withIntermediateDirectories: true)
        try shellHookContent()
            .write(to: shellHook, atomically: true, encoding: .utf8)

        let shellFiles = [
            homeDirectory.appendingPathComponent(".zshrc"),
            homeDirectory.appendingPathComponent(".bashrc")
        ]

        for shellFile in shellFiles {
            try appendSourceBlockIfNeeded(to: shellFile)
        }

        return shellFiles
    }

    public func isShellHookInstalled() -> Bool {
        [
            homeDirectory.appendingPathComponent(".zshrc"),
            homeDirectory.appendingPathComponent(".bashrc")
        ].contains { shellFile in
            guard let contents = try? String(contentsOf: shellFile, encoding: .utf8) else {
                return false
            }
            return contents.contains(beginMarker)
        }
    }

    public func activeProfileEnvContent(for profile: CodexProfile) -> String {
        """
        # Generated by Codex Model Switcher. Do not put secrets here.
        export CODEX_HOME=\(shellEscape(profile.path))
        export CODEX_MODEL_SWITCHER_ACTIVE_PROFILE_ID=\(shellEscape(profile.id))
        export CODEX_MODEL_SWITCHER_ACTIVE_PROFILE_NAME=\(shellEscape(profile.name))
        """
        + "\n"
    }

    public func shellHookContent() -> String {
        """
        # Codex Model Switcher shell hook
        _codex_model_switcher_active_profile_env=\(shellEscape(activeProfileEnv.path))

        codex() {
          if [ -f "$_codex_model_switcher_active_profile_env" ]; then
            . "$_codex_model_switcher_active_profile_env"
          fi
          command codex "$@"
        }
        """
        + "\n"
    }

    private func appendSourceBlockIfNeeded(to shellFile: URL) throws {
        let existing = (try? String(contentsOf: shellFile, encoding: .utf8)) ?? ""
        guard !existing.contains(beginMarker) else { return }

        if !fileManager.fileExists(atPath: shellFile.deletingLastPathComponent().path) {
            try fileManager.createDirectory(
                at: shellFile.deletingLastPathComponent(),
                withIntermediateDirectories: true
            )
        }

        var updated = existing
        if !updated.isEmpty, !updated.hasSuffix("\n") {
            updated += "\n"
        }
        if !updated.isEmpty {
            updated += "\n"
        }
        updated += sourceBlock()
        try updated.write(to: shellFile, atomically: true, encoding: .utf8)
    }

    private func sourceBlock() -> String {
        """
        \(beginMarker)
        if [ -f \(shellEscape(shellHook.path)) ]; then
          . \(shellEscape(shellHook.path))
        fi
        \(endMarker)
        """
        + "\n"
    }

    private func shellEscape(_ value: String) -> String {
        "'" + value.replacingOccurrences(of: "'", with: "'\\''") + "'"
    }
}
